
spring:
  application:
    name: zuul-api-gateway-server
    
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
server:
  port: 8765
  
